#!/usr/bin/env bash
#4th bad 8th gool others Best School
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
         echo "bad luck"
	 ((count++))
    elif [ $count -eq 8 ]; then
	echo "good luck"
        ((count++))
    else
	echo "Best School"
        ((count++))
    fi
done
