#!/usr/bin/env bash
#....
count=1
while [ $count -le 20 ]; do
    case $count in
       5)
	 echo "bad luck from China"
          ;;
       10)
         echo "bad luck from Japan"
          ;;
       18)
         echo "bad luck from Italy"
          ;;
       esac
       echo "$count"
       ((count++))
done
