#!/usr/bin/env bash
#....
while [ {1..20} ]; do
    case $count in
       4)
	 echo "bad luck from China"
          ;;
       9)
         echo "bad luck from Japan"
          ;;
       17)
         echo "bad luck from Italy"
          ;;
       esac
       echo "Best School"
done
