#!/usr/bin/env bash
#Comment
if [ -e school ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi
if [ -s school ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f school ]; then
    echo "dchool file is a regular file"
fi
