#!/usr/bin/env bash
#Comment
echo "File name is school" >> school.txt
if [ -e school.txt ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi
if [ -s school.txt ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f school.txt ]; then
    echo "school file is a regular file"
fi
