#!/usr/bin/env bash
#Comment
if [ -e school.txt ]; then
    echo "school file exists"
    if [ ! -s school.txt ]; then
        echo "school file is not empty"
        if [ -f school.txt ]; then
        echo "school file is a regular file"
        fi
    else
        echo "school file is empty"
    fi
    
else
    echo "school file does not exist"
fi

